let
    // Step 1: Load the initial table
    Source = <Your Dataverse Source>,  // Replace with your data source

    // Step 2: Get a list of columns in the table
    Columns = Table.ColumnNames(Source),

    // Step 3: Identify columns to expand (those with "_name" or "_label" suffix)
    LookupColumns = List.Select(Columns, each Text.EndsWith(_, "_name")),
    ChoiceColumns = List.Select(Columns, each Text.EndsWith(_, "_label")),

    // Step 4: Expand these columns
    ExpandedLookups = Table.TransformColumns(Source, List.Transform(LookupColumns, each {_, Text.Lower})),
    ExpandedChoices = Table.TransformColumns(ExpandedLookups, List.Transform(ChoiceColumns, each {_, Text.Lower})),

    // Optional: Rename expanded columns to be user-friendly
    RenamedColumns = Table.RenameColumns(ExpandedChoices, List.Transform(LookupColumns & ChoiceColumns, each {_, Text.BeforeDelimiter(_, "_")}))
in
    RenamedColumns
